Feature/progress bar
adopt-liveview/adopt-liveview pull request #63
Opened 2024-10-03 11:43 UTC by dmitry-sidorov

@lubien What's up!

I've implemented a progress bar for this beautiful and useful LiveView tutorial.
Review it, please.

Best regards 😄 

https://github.com/user-attachments/assets/82ca45f2-fb80-44b3-8b0d-97990efcdaab

2024-10-11 11:54 UTC, lubien commented on README.md
> +  * Create database container `docker run --name curso_dev -p 5432:5432 -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=postgres -d postgres`
I dont think we need that!

2024-10-11 11:55 UTC, lubien commented on lib/curso_web/components/core_components.ex
> +    assigns |> dbg()
Can you remove this line?

2024-10-11 11:56 UTC, lubien commented on lib/curso_web/live/guide_live.ex
> +  @spec render(any()) :: Phoenix.LiveView.Rendered.t()
Can you remove this line?

2024-10-11 11:56 UTC, lubien requested changes
Great stuff! Asked some minor changes

2024-10-11 14:09 UTC, dmitry-sidorov commented on README.md
> +  * Create database container `docker run --name curso_dev -p 5432:5432 -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=postgres -d postgres`
Removed!

2024-10-11 14:09 UTC, dmitry-sidorov commented on lib/curso_web/live/guide_live.ex
> +  @spec render(any()) :: Phoenix.LiveView.Rendered.t()
Autoformatter, I guess

2024-10-26 18:51 UTC, dmitry-sidorov commented
@lubien up

2024-11-05 07:47 UTC, dmitry-sidorov commented
@lubien Hey, man! I hope you're doing well! Could you, please, review these tiny fixes and we'll be able to merge it and improve this cool project?

2024-11-14 13:44 UTC, lubien approved these changes

2024-11-14 13:44 UTC, merged